name: delta_notifier
description: Provides AnimatedDeltaBuilder<T>, allowing you to pass data to the builder function from your DeltaListenable<T> model.
version: 0.0.1
author: Kieran <kieran+git@harkin.me>
homepage: https://github.com/v0l/delta_notifer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
